export const searchResult = {
	items: [
		{
			tags: [
				'python',
				'django',
				'bootstrap-4',
				'modal-dialog',
				'bootstrap-modal',
			],
			owner: {
				account_id: 28469309,
				reputation: 11,
				user_id: 21784876,
				user_type: 'registered',
				profile_image:
					'https://lh3.googleusercontent.com/a/AGNmyxacolDIhscs1BngoYj08TATZ3OzB6xHPlBMlV0jNA=k-s256',
				display_name: 'ade tri',
				link: 'https://stackoverflow.com/users/21784876/ade-tri',
			},
			is_answered: false,
			view_count: 5,
			answer_count: 0,
			score: 1,
			last_activity_date: 1682922782,
			creation_date: 1682922782,
			question_id: 76145113,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76145113/django-bootstap-modals-cant-render-modal-content',
			title: 'Django Bootstap Modals cant render modal content',
		},
		{
			tags: ['django', 'task', 'threadpoolexecutor'],
			owner: {
				account_id: 27998736,
				reputation: 15,
				user_id: 21383431,
				user_type: 'registered',
				profile_image:
					'https://lh3.googleusercontent.com/a/AGNmyxbV50dZ156M6dp3eio1RlbuCoj8yNuwU2XheF69=k-s256',
				display_name: '0x Empyrean',
				link: 'https://stackoverflow.com/users/21383431/0x-empyrean',
			},
			is_answered: false,
			view_count: 10,
			answer_count: 0,
			score: 0,
			last_activity_date: 1682919880,
			creation_date: 1682919880,
			question_id: 76144945,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76144945/how-to-run-tasks-in-django',
			title: 'How to run tasks in django?',
		},
		{
			tags: ['django', 'django-staticfiles'],
			owner: {
				account_id: 28421883,
				reputation: 23,
				user_id: 21743846,
				user_type: 'registered',
				profile_image: 'https://i.stack.imgur.com/AGj5e.jpg?s=256&g=1',
				display_name: 'Łukasz Jasiński',
				link: 'https://stackoverflow.com/users/21743846/%c5%81ukasz-jasi%c5%84ski',
			},
			is_answered: false,
			view_count: 14,
			answer_count: 1,
			score: 0,
			last_activity_date: 1682919846,
			creation_date: 1682915886,
			question_id: 76144745,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76144745/django-i-cant-display-any-image',
			title: 'Django: I can&#39;t display any image',
		},
		{
			tags: [
				'sql',
				'django',
				'angular',
				'django-models',
				'django-rest-framework',
			],
			owner: {
				account_id: 22843571,
				reputation: 1,
				user_id: 16990197,
				user_type: 'registered',
				profile_image:
					'https://lh3.googleusercontent.com/a-/AOh14Gj_mKwI6oKfPpHGWJ8xxMPeH78YDSQuUR4Cbp6Fng=k-s256',
				display_name: 'Pratish Dewangan',
				link: 'https://stackoverflow.com/users/16990197/pratish-dewangan',
			},
			is_answered: false,
			view_count: 11,
			answer_count: 0,
			score: 0,
			last_activity_date: 1682919696,
			creation_date: 1682919696,
			question_id: 76144933,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76144933/how-to-get-tables-from-sql-to-angular-viadjango-as-backend-by-not-using-any-mode',
			title:
				'How to get tables from SQL to Angular viaDjango as backend by not using any models in Django,',
		},
		{
			tags: ['django', 'django-rest-framework', 'django-templates'],
			owner: {
				account_id: 21613098,
				reputation: 1,
				user_id: 15939316,
				user_type: 'registered',
				profile_image:
					'https://lh3.googleusercontent.com/a-/AOh14GgVCt6ImuVlVhFrsaV5fRJ2o7bmCIHQEiov7OsvTQ=k-s256',
				display_name: 'pekka 123',
				link: 'https://stackoverflow.com/users/15939316/pekka-123',
			},
			is_answered: false,
			view_count: 20,
			answer_count: 0,
			score: 0,
			last_activity_date: 1682906136,
			creation_date: 1682906136,
			question_id: 76144377,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76144377/django-invalid-tag-error-is-showing-up-everytime',
			title: 'Django invalid tag error is showing up everytime',
		},
		{
			tags: ['django', 'django-rest-framework', 'cdc'],
			owner: {
				account_id: 15903679,
				reputation: 51,
				user_id: 11475443,
				user_type: 'registered',
				profile_image:
					'https://www.gravatar.com/avatar/cdc7c535f3d05c91e81d95cf0d640fb5?s=256&d=identicon&r=PG&f=1',
				display_name: 'Nicnem',
				link: 'https://stackoverflow.com/users/11475443/nicnem',
			},
			is_answered: false,
			view_count: 16,
			answer_count: 0,
			score: 0,
			last_activity_date: 1682906126,
			creation_date: 1682837392,
			last_edit_date: 1682906126,
			question_id: 76139908,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76139908/what-is-the-simplest-way-to-implement-cdc-in-a-monolithic-django-project-with-my',
			title:
				'What is the simplest way to implement CDC in a monolithic Django project with MySQL DB?',
		},
		{
			tags: ['python', 'django'],
			owner: {
				account_id: 23931742,
				reputation: 58,
				user_id: 19420551,
				user_type: 'registered',
				profile_image:
					'https://www.gravatar.com/avatar/6efd2f8151315c5edb189147b7761cab?s=256&d=identicon&r=PG&f=1',
				display_name: 'Bamagujen_Bahaushe.',
				link: 'https://stackoverflow.com/users/19420551/bamagujen-bahaushe',
			},
			is_answered: false,
			view_count: 86,
			bounty_amount: 50,
			bounty_closes_date: 1683386322,
			answer_count: 1,
			score: -3,
			last_activity_date: 1682904230,
			creation_date: 1682603117,
			last_edit_date: 1682684621,
			question_id: 76121140,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76121140/can-we-use-opencv-to-detect-nudes-object-in-django',
			title: 'Can we use OpenCv to detect Nudes object in django',
		},
		{
			tags: ['python', 'django', 'django-rest-framework'],
			owner: {
				account_id: 8914592,
				reputation: 3466,
				user_id: 6653602,
				user_type: 'registered',
				accept_rate: 80,
				profile_image:
					'https://www.gravatar.com/avatar/308958dfcf4e6e51275ac0a387a24363?s=256&d=identicon&r=PG&f=1',
				display_name: 'Alex T',
				link: 'https://stackoverflow.com/users/6653602/alex-t',
			},
			is_answered: false,
			view_count: 66,
			bounty_amount: 50,
			bounty_closes_date: 1683267036,
			answer_count: 1,
			score: 0,
			last_activity_date: 1682896833,
			creation_date: 1682481906,
			question_id: 76107092,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76107092/django-using-prefetch-related-to-reduce-queries',
			title: 'Django using prefetch_related to reduce queries',
		},
		{
			tags: ['python', 'django', 'docker', 'kubernetes'],
			owner: {
				account_id: 18307083,
				reputation: 449,
				user_id: 13330700,
				user_type: 'registered',
				profile_image:
					'https://www.gravatar.com/avatar/26c4be5ebc5d23f53462bc078dd604b4?s=256&d=identicon&r=PG&f=1',
				display_name: 'mike_gundy123',
				link: 'https://stackoverflow.com/users/13330700/mike-gundy123',
			},
			is_answered: false,
			view_count: 33,
			answer_count: 0,
			score: 0,
			last_activity_date: 1682895474,
			creation_date: 1682895474,
			question_id: 76143920,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76143920/kubernetes-health-check-always-fails-for-django-application',
			title: 'Kubernetes health check always fails for django application',
		},
		{
			tags: ['python', 'django'],
			owner: {
				account_id: 28189114,
				reputation: 1,
				user_id: 21773963,
				user_type: 'registered',
				profile_image:
					'https://lh3.googleusercontent.com/a/AGNmyxZ8MRqfuLcUa2qmwtCAq6gvBgS7dpJZ5B3M-SgXYQ=k-s256',
				display_name: 'Дима Бирилко',
				link: 'https://stackoverflow.com/users/21773963/%d0%94%d0%b8%d0%bc%d0%b0-%d0%91%d0%b8%d1%80%d0%b8%d0%bb%d0%ba%d0%be',
			},
			is_answered: false,
			view_count: 16,
			answer_count: 0,
			score: 0,
			last_activity_date: 1682894511,
			creation_date: 1682787287,
			last_edit_date: 1682894511,
			question_id: 76137375,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76137375/password-reset-in-django',
			title: 'Password reset in Django',
		},
	],
	has_more: true,
	quota_max: 10000,
	quota_remaining: 9995,
};

export const questionsByAuthor = {
	items: [
		{
			tags: [
				'python',
				'django',
				'bootstrap-4',
				'modal-dialog',
				'bootstrap-modal',
			],
			owner: {
				account_id: 28469309,
				reputation: 11,
				user_id: 21784876,
				user_type: 'registered',
				profile_image:
					'https://lh3.googleusercontent.com/a/AGNmyxacolDIhscs1BngoYj08TATZ3OzB6xHPlBMlV0jNA=k-s256',
				display_name: 'ade tri',
				link: 'https://stackoverflow.com/users/21784876/ade-tri',
			},
			is_answered: false,
			view_count: 6,
			answer_count: 0,
			score: 1,
			last_activity_date: 1682922782,
			creation_date: 1682922782,
			question_id: 76145113,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76145113/django-bootstap-modals-cant-render-modal-content',
			title: 'Django Bootstap Modals cant render modal content',
			body: "<p>im trying to create a simple popup with Django Bootstrap Modal. but I can't get linked content at modals body, and when im trying to access a content its there. im so confused why my linked content cant render at modals body</p>\n<p>base.html</p>\n<pre><code>&lt;!doctype html&gt;\n&lt;html lang=&quot;en&quot;&gt;\n  &lt;head&gt;\n    &lt;!-- Required meta tags --&gt;\n    &lt;meta charset=&quot;utf-8&quot;&gt;\n    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;\n\n    &lt;!-- Bootstrap CSS --&gt;\n    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css&quot;&gt;\n\n    &lt;title&gt;Hello, world!&lt;/title&gt;\n  &lt;/head&gt;\n  &lt;body&gt;\n        &lt;a href=&quot;{% url 'form_view' %}&quot; class=&quot;btn btn-primary btn-lg&quot; data-toggle=&quot;modal&quot; data-target=&quot;#myModal&quot;&gt;\n        Open Form Modal\n        &lt;/a&gt;\n\n        &lt;!-- Modal --&gt;\n        &lt;div class=&quot;modal fade&quot; id=&quot;myModal&quot; tabindex=&quot;-1&quot; role=&quot;dialog&quot; aria-labelledby=&quot;myModalLabel&quot;&gt;\n        &lt;div class=&quot;modal-dialog&quot; role=&quot;document&quot;&gt;\n            &lt;div class=&quot;modal-content&quot;&gt;\n            &lt;div class=&quot;modal-header&quot;&gt;\n                &lt;h4 class=&quot;modal-title&quot; id=&quot;myModalLabel&quot;&gt;Form Modal&lt;/h4&gt;\n                &lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;modal&quot; aria-label=&quot;Close&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/span&gt;&lt;/button&gt;\n            &lt;/div&gt;\n            &lt;div class=&quot;modal-body&quot;&gt;\n                &lt;!-- Your form goes here --&gt;\n            &lt;/div&gt;\n            &lt;/div&gt;\n        &lt;/div&gt;\n        &lt;/div&gt;\n\n    &lt;!-- Optional JavaScript --&gt;\n    &lt;!-- Bootstrap JavaScript --&gt;\n&lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js&quot;&gt;&lt;/script&gt;\n&lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js&quot;&gt;&lt;/script&gt;\n&lt;script src=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js&quot;&gt;&lt;/script&gt;\n  &lt;/body&gt;\n&lt;/html&gt;\n\n&lt;!-- Bootstrap CSS --&gt;\n\n\n\n</code></pre>\n<p>form_view.html</p>\n<pre><code>&lt;form method=&quot;post&quot; action=&quot;{% url 'form_submit' %}&quot;&gt;\n  {% csrf_token %}\n  &lt;div class=&quot;form-group&quot;&gt;\n    &lt;label for=&quot;{{ form.name.id_for_label }}&quot;&gt;Name:&lt;/label&gt;\n    {{ form.name }}\n  &lt;/div&gt;\n  &lt;div class=&quot;form-group&quot;&gt;\n    &lt;label for=&quot;{{ form.email.id_for_label }}&quot;&gt;Email:&lt;/label&gt;\n    {{ form.email }}\n  &lt;/div&gt;\n  &lt;div class=&quot;form-group&quot;&gt;\n    &lt;label for=&quot;{{ form.message.id_for_label }}&quot;&gt;Message:&lt;/label&gt;\n    {{ form.message }}\n  &lt;/div&gt;\n  &lt;button type=&quot;submit&quot; class=&quot;btn btn-primary&quot;&gt;Submit&lt;/button&gt;\n&lt;/form&gt;\n\n</code></pre>\n<p>views.py</p>\n<pre><code>from .forms import MyForm\nfrom django.shortcuts import render, redirect\n\n\n\ndef example_view(request):\n    return render(request, 'base.html')\n\n\ndef form_submit(request):\n    if request.method == 'POST':\n        form = MyForm(request.POST)\n        if form.is_valid():\n            # Process the form data\n            name = form.cleaned_data['name']\n            email = form.cleaned_data['email']\n            message = form.cleaned_data['message']\n            # Redirect to a success page\n            return redirect('success_view')\n    else:\n        form = MyForm()\n    return render(request, 'form_template.html', {'form': form})\n\n\ndef form_view(request):\n    form = MyForm()\n    return render(request, 'form_template.html', {'form': form})\n\n</code></pre>\n<p>i want to inject form_view.html into modals at base.html</p>\n",
		},
	],
	has_more: false,
	quota_max: 10000,
	quota_remaining: 9980,
};

export const questionsByTag = {
	items: [
		{
			tags: ['stored-procedures', 'db2'],
			owner: {
				account_id: 22119133,
				reputation: 13,
				user_id: 16372698,
				user_type: 'registered',
				profile_image:
					'https://lh3.googleusercontent.com/a-/AOh14Gh9_ykiPW-G1FVXeKQxd-wm7RX1L9mYbnJvv8FjsQ=k-s256',
				display_name: 'UDAYA KUMAR R',
				link: 'https://stackoverflow.com/users/16372698/udaya-kumar-r',
			},
			is_answered: false,
			view_count: 10,
			answer_count: 0,
			score: 0,
			last_activity_date: 1682917785,
			creation_date: 1682917197,
			last_edit_date: 1682917785,
			question_id: 76144801,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76144801/db2-stored-procedure-create-three-tables-in-single-store-procedure',
			title:
				'DB2 stored procedure - Create three tables in single store procedure',
			body: '<p>I am new to stored procedures. I need to create 3 tables (table A, table B, table C) while executing one single stored procedure. Is this possible?</p>\n<p>If it is possible, please provide the skeleton of the stored procedure.</p>\n<p>Thanks in advance.</p>\n',
		},
		{
			tags: ['sql', 'stored-procedures', 'db2'],
			owner: {
				account_id: 2108281,
				reputation: 765,
				user_id: 1874087,
				user_type: 'registered',
				accept_rate: 87,
				profile_image: 'https://i.stack.imgur.com/uLyUm.jpg?s=256&g=1',
				display_name: 'Tone',
				link: 'https://stackoverflow.com/users/1874087/tone',
			},
			is_answered: false,
			view_count: 13612,
			answer_count: 1,
			score: 2,
			last_activity_date: 1682903160,
			creation_date: 1400529464,
			last_edit_date: 1400613584,
			question_id: 23746173,
			content_license: 'CC BY-SA 3.0',
			link: 'https://stackoverflow.com/questions/23746173/db2-stored-procedure-w-parameters',
			title: 'DB2 stored procedure w/ parameters',
			body: "<p>I'm having a hard time producing the correct results from my stored procedure.  I'm using a db2 database and I have 3 input parameters division, department, project.  My call statement looks like this.</p>\n\n<pre><code>CALL schema.stored_procedure ('IT', 'MARKETING', 'ONLINE FULFILLMENT')\n</code></pre>\n\n<p>I need to produce results that will display the row of data when the third parameter is specified or has a value for the Project Name (as from the example above <strong>'Online_fulfillment'</strong>) and to display all the results when the third parameter has a value 'ALL' for Project Name (per the example below <strong>'ALL'</strong>).  </p>\n\n<pre><code>CALL schema.stored_procedure ('IT', 'MARKETING', 'ALL')\n</code></pre>\n\n<p>My query below currently is returning just the column header names with no results and I'm having trouble debugging it.  Here is my current stored procedure.</p>\n\n<pre><code>CREATE PROCEDURE schema.stored_procedure\n  (IN in_DIVISION_NAME VARCHAR(200)\n  ,IN in_DEPARTMENT_NAME VARCHAR(20)\n  ,IN in_PROJECT_NAME VARCHAR(400)\n  )\n  DYNAMIC RESULT SETS 1\n BEGIN\n  IF (in_PROJECT_NAME = 'ALL') THEN\n   BEGIN\n    DECLARE GLOBAL TEMPORARY TABLE TEMP_DW_1\n      (DIM_PROJECT_ID INT \n      ,PROJECT_NAME VARCHAR (400) \n      ,DIM_DEPARTMENT_ID INT  \n      ,DEPARTMENT_NAME VARCHAR(100) \n      ,DIVISION_NAME VARCHAR(100)  \n      ) ON COMMIT DELETE ROWS NOT LOGGED WITH REPLACE;\n   END;\n\n    INSERT INTO SESSION.TEMP_DW_1 (DIM_PROJECT_ID, PROJECT_NAME, DIM_DEPARTMENT_ID,\n      DEPARTMENT_NAME,DIVISION_NAME)\n             SELECT DISTINCT DJ.DIM_PROJECT_ID\n            ,PROJECT_NAME\n            ,DIM_DEPARTMENT_ID\n            ,DEPARTMENT_NAME\n            ,DIVISION_NAME\n                 FROM SCHEMA.FACT_TABLE \n                 WHERE DEPARTMENT_NAME =  in_DEPARTMENT_NAME\n                 AND DIVISION_NAME =  in_DIVISION_NAME; \n\n          BEGIN\n        DECLARE  exitCursor CURSOR WITH RETURN FOR\n        SELECT * \n        FROM SESSION.TEMP_DW_1;\n\n        OPEN exitCursor;\n\n           END;\n END \n</code></pre>\n\n<p>EXPECTED RESULTS:\nCALL schema.stored_procedure ('IT', 'MARKETING', 'ONLINE FULFILLMENT')\n<img src=\"https://i.stack.imgur.com/Y5V6Z.png\" alt=\"enter image description here\">\nEXPECTED RESULTS:\nCALL schema.stored_procedure ('IT', 'MARKETING', 'ALL')\n<img src=\"https://i.stack.imgur.com/RQirH.png\" alt=\"enter image description here\"></p>\n",
		},
		{
			tags: ['spring-boot', 'db2', 'ibm-midrange'],
			owner: {
				account_id: 12468251,
				reputation: 31,
				user_id: 9077363,
				user_type: 'registered',
				profile_image:
					'https://www.gravatar.com/avatar/a177adbb4e71cc780b9a2b209e367946?s=256&d=identicon&r=PG&f=1',
				display_name: 'Grigory Tsureyev',
				link: 'https://stackoverflow.com/users/9077363/grigory-tsureyev',
			},
			is_answered: true,
			view_count: 5283,
			answer_count: 3,
			score: 1,
			last_activity_date: 1682799839,
			creation_date: 1612337478,
			question_id: 66023013,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/66023013/as400-spring-boot-java-connection',
			title: 'AS400 Spring Boot Java Connection',
			body: '<p>I am having following exeption trying to connect to db</p>\n<p><code>HikariPool-1 - Driver does not support get/set network timeout for connections. (Receiver class com.ibm.as400.access.AS400JDBCConnectionImpl does not define or inherit an implementation of the resolved method abstract setNetworkTimeout(Ljava/util/concurrent/Executor;I)V of interface java.sql.Connection.) </code></p>\n<p>This is my pom</p>\n<pre><code>&lt;dependencies&gt;\n       &lt;dependency&gt;\n           &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n           &lt;artifactId&gt;spring-boot-starter-data-jpa&lt;/artifactId&gt;\n       &lt;/dependency&gt;\n       &lt;dependency&gt;\n           &lt;groupId&gt;net.sf.jt400&lt;/groupId&gt;\n           &lt;artifactId&gt;jt400&lt;/artifactId&gt;\n           &lt;version&gt;10.5&lt;/version&gt;\n       &lt;/dependency&gt;\n   &lt;/dependencies&gt; \n</code></pre>\n<p>And application yaml</p>\n<pre><code>spring.datasource:\n  url: jdbc:as400://xxx/xxx\n  username: xxx\n  password: xxx\n  driver-class-name: com.ibm.as400.access.AS400JDBCDriver\n  hikari.connection-test-query: values 1\nspring.jpa:\n  database-platform: org.hibernate.dialect.DB2400Dialect\n  hibernate.ddl-auto: none\n</code></pre>\n',
		},
		{
			tags: ['python-3.x', 'windows', 'cmd', 'pip', 'db2'],
			owner: {
				account_id: 26219331,
				reputation: 1,
				user_id: 19897033,
				user_type: 'registered',
				profile_image:
					'https://lh3.googleusercontent.com/a-/AFdZucrZK5Gy78c7Ce3qQG9dnUYsjyC6wibLRGVumcqb=k-s256',
				display_name: 'Muzan Jackson',
				link: 'https://stackoverflow.com/users/19897033/muzan-jackson',
			},
			is_answered: false,
			view_count: 22,
			closed_date: 1682788519,
			answer_count: 0,
			score: -1,
			last_activity_date: 1682781292,
			creation_date: 1682766978,
			last_edit_date: 1682781292,
			question_id: 76135913,
			link: 'https://stackoverflow.com/questions/76135913/oserror-errno-9-bad-file-descriptor-while-using-pip-command-in-python-when-in',
			closed_reason: 'Not suitable for this site',
			title:
				'OSError: [Errno 9] Bad file descriptor while using pip command in python when installing ibm db',
			body: "<p>I'm trying to install ibm db pip module on python 3.11 64bit then I got these following error</p>\n<p>Please help</p>\n<pre><code>\nC:\\Users\\Admin&gt;py -m pip install ibm_db -v\nUsing pip 23.1.2 from C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pip (python 3.11)\nCollecting ibm_db\n  Using cached ibm_db-3.1.4.tar.gz (1.4 MB)\n  Running command pip subprocess to install build dependencies\n  Collecting setuptools\n    Using cached setuptools-67.7.2-py3-none-any.whl (1.1 MB)\n  Installing collected packages: setuptools\n  Successfully installed setuptools-67.7.2\n  Installing build dependencies ... done\n  Running command Getting requirements to build wheel\n  Detected 64-bit Python\n  Detected platform = win32\n  Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip\n   Downloading DSDriver from url =  https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip\n  running egg_info\n  writing ibm_db.egg-info\\PKG-INFO\n  writing dependency_links to ibm_db.egg-info\\dependency_links.txt\n  writing top-level names to ibm_db.egg-info\\top_level.txt\n  reading manifest file 'ibm_db.egg-info\\SOURCES.txt'\n  reading manifest template 'MANIFEST.in'\n  warning: no previously-included files found matching 'config.py'\n  adding license file 'LICENSE'\n  writing manifest file 'ibm_db.egg-info\\SOURCES.txt'\n\n  ****************************************\n  You are downloading a package which includes the Python module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the python module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\clidriver or C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ibm_db-3.1.4-py3.1.egg\\clidriver.   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.\n  ****************************************\n  Getting requirements to build wheel ... done\n  Running command pip subprocess to install backend dependencies\n  Collecting wheel\n    Using cached wheel-0.40.0-py3-none-any.whl (64 kB)\n  Installing collected packages: wheel\n  Successfully installed wheel-0.40.0\n  Installing backend dependencies ... done\n  Running command Preparing metadata (pyproject.toml)\n  Detected 64-bit Python\n  Detected platform = win32\n  running dist_info\n  creating C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-modern-metadata-qse4ttet\\ibm_db.egg-info\n  writing C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-modern-metadata-qse4ttet\\ibm_db.egg-info\\PKG-INFO\n  writing dependency_links to C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-modern-metadata-qse4ttet\\ibm_db.egg-info\\dependency_links.txt\n  writing top-level names to C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-modern-metadata-qse4ttet\\ibm_db.egg-info\\top_level.txt\n  writing manifest file 'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-modern-metadata-qse4ttet\\ibm_db.egg-info\\SOURCES.txt'\n  reading manifest file 'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-modern-metadata-qse4ttet\\ibm_db.egg-info\\SOURCES.txt'\n  reading manifest template 'MANIFEST.in'\n  warning: no previously-included files found matching 'config.py'\n  adding license file 'LICENSE'\n  writing manifest file 'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-modern-metadata-qse4ttet\\ibm_db.egg-info\\SOURCES.txt'\n  creating 'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-modern-metadata-qse4ttet\\ibm_db-3.1.4.dist-info'\n\n  ****************************************\n  You are downloading a package which includes the Python module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the python module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\clidriver or C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ibm_db-3.1.4-py3.1.egg\\clidriver.   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.\n  ****************************************\n  OSError: [Errno 9] Bad file descriptor\n\n  During handling of the above exception, another exception occurred:\n\n  Traceback (most recent call last):\n    File &quot;C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pip\\_vendor\\pyproject_hooks\\_in_process\\_in_process.py&quot;, line 353, in &lt;module&gt;\n      main()\n    File &quot;C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pip\\_vendor\\pyproject_hooks\\_in_process\\_in_process.py&quot;, line 349, in main\n      write_json(json_out, pjoin(control_dir, 'output.json'), indent=2)\n    File &quot;C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pip\\_vendor\\pyproject_hooks\\_in_process\\_in_process.py&quot;, line 31, in write_json\n      with open(path, 'w', encoding='utf-8') as f:\n  OSError: [Errno 9] Bad file descriptor\n  error: subprocess-exited-with-error\n\n  × Preparing metadata (pyproject.toml) did not run successfully.\n  │ exit code: 1\n  ╰─&gt; See above for output.\n\n  note: This error originates from a subprocess, and is likely not a problem with pip.\n  full command: 'C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\python.exe' 'C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pip\\_vendor\\pyproject_hooks\\_in_process\\_in_process.py' prepare_metadata_for_build_wheel 'C:\\Users\\Admin\\AppData\\Local\\Temp\\tmp8tcg0ise'\n  cwd: C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-o4ztkyco\\ibm-db_a13dacf9287d420f9e0b5be6b0cc847d\n  Preparing metadata (pyproject.toml) ... error\nerror: metadata-generation-failed\n\n× Encountered error while generating package metadata.\n╰─&gt; See above for output.\n\nnote: This is an issue with the package mentioned above, not pip.\nhint: See above for details.\n</code></pre>\n<p>I have tried to set IBM_DB_HOME to clidriver but it returns other error like can't build wheel.I have also tried setting IBM_DB_HOME to the location where the driver is installed but it also doesn't help</p>\n<p>There were no commands executed before <code>py -m pip install ibm-db -v</code><br>\nI have installed IBM DATA DRIVER on the system<br></p>\n<p>Do I need any other libraries to install this module as I have fresh install of python 3.11 or is there any other python 3.x version I can use for this?</p>\n",
		},
		{
			tags: ['sql', 'sqlalchemy', 'db2', 'python-db-api'],
			owner: {
				account_id: 21545348,
				reputation: 11,
				user_id: 15882282,
				user_type: 'registered',
				profile_image:
					'https://www.gravatar.com/avatar/979c7907f5cfd20b42b63db8cbd005e0?s=256&d=identicon&r=PG&f=1',
				display_name: 'Le Hoang Phuc',
				link: 'https://stackoverflow.com/users/15882282/le-hoang-phuc',
			},
			is_answered: true,
			view_count: 3559,
			answer_count: 4,
			score: 1,
			last_activity_date: 1682770271,
			creation_date: 1620615043,
			last_edit_date: 1620624181,
			question_id: 67464195,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/67464195/ibm-db2-an-unexpected-token-as-was-found-following-select-test-score-sql',
			title:
				'IBM Db2 : An unexpected token &quot;as&quot; was found following &quot;SELECT test_score &quot; (SQL0104N)',
			body: '<p>I am now having trouble with IBM Db2 using queries. I have a code below:</p>\n<pre><code>test_score_distribution = %sql SELECT test_score as &quot;Test Score&quot;, count(*) as &quot;Frequency&quot; from INTERNATIONAL_STUDENT_TEST_SCORES GROUP BY test_score;\n\ntest_score_distribution\n</code></pre>\n<p>But when executing, I encountered this error:</p>\n<blockquote>\n<p>(ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError:\nSQLNumResultCols failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N\nAn unexpected token &quot;as&quot; was found following &quot;SELECT test_score &quot;.\nExpected tokens may include:  &quot;AND&quot;.  SQLSTATE=42601\\r SQLCODE=-104\n[SQL: SELECT test_score as Test Score, count(*) as Frequency from\nINTERNATIONAL_STUDENT_TEST_SCORES GROUP BY test_score;] (Background on\nthis error at: http://sqlalche.me/e/f405)</p>\n</blockquote>\n<p>How can i fix it?</p>\n',
		},
		{
			tags: ['db2', 'db2-luw'],
			owner: {
				account_id: 26589839,
				reputation: 17,
				user_id: 20213228,
				user_type: 'registered',
				profile_image:
					'https://lh3.googleusercontent.com/a/ALm5wu04j8VQne8TfcgvQeYaSCfYVMZIa65iQAiReDRR=k-s256',
				display_name: 'DB2fan',
				link: 'https://stackoverflow.com/users/20213228/db2fan',
			},
			is_answered: false,
			view_count: 47,
			answer_count: 1,
			score: 0,
			last_activity_date: 1682748526,
			creation_date: 1682689242,
			last_edit_date: 1682705897,
			question_id: 76130174,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76130174/db2-prechecks-in-stored-procedure-using-mulitple-conditions',
			title: 'DB2 Prechecks in stored procedure using mulitple conditions',
			body: "<p>I am calling a stored procedure which should make some prechecks.\nCurrently I am going through all checks. When one check is failed, than it should throw the exception.</p>\n<p>How can I realize it?</p>\n<pre><code>DECLARE VSTRING VARCHAR(1);\n\nSELECT * INTO VSTRING\nFROM\n(SELECT 'A'\nFROM A WHERE ID = xxx)\nUNION ALL \n(SELECT 'B'\nFROM B WHERE xxx)\n\nIF(VSTRING IS NOT NULL) THEN\nSIGNAL SQLSTATE '0101' SET MESSAGE_TEXT = 'Violation ...' || VSTRING;\nEND IF\n</code></pre>\n",
		},
		{
			tags: ['sql', 'validation', 'db2', 'connection', 'wildfly'],
			owner: {
				account_id: 20543565,
				reputation: 1,
				user_id: 15077974,
				user_type: 'registered',
				profile_image:
					'https://www.gravatar.com/avatar/7546130c4c91d89a716d68e19299b1bc?s=256&d=identicon&r=PG&f=1',
				display_name: 'Dima',
				link: 'https://stackoverflow.com/users/15077974/dima',
			},
			is_answered: true,
			view_count: 33,
			answer_count: 1,
			score: 0,
			last_activity_date: 1682703080,
			creation_date: 1682692631,
			question_id: 76130678,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76130678/db2-sql-error-sqlcode-104-sqlstate-42601-sqlerrmc-begin-select-driver',
			title:
				'DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=*;begin select ;(, DRIVER=4.19.26',
			body: '<p>I am relatively new to DB2 but not to SQL. I am experiencing the below error when trying a SELECT statement</p>\n<pre><code>&lt;validation&gt;\n   &lt;validate-on-match&gt;true&lt;/validate-on-match&gt;\n   &lt;background-validation&gt;true&lt;/background-validation&gt;\n   &lt;background-validation-millis&gt;60000&lt;/background-validation-millis&gt;\n   &lt;check-valid-connection-sql&gt;begin; select * from DBSCHEMA.DB_VALIDITY_CHECK where CHECKER = 1 for update; commit;&lt;/check-valid-connection-sql&gt;\n</code></pre>\n<p>can someone help me</p>\n<p>tried to change the sql:</p>\n<ol>\n<li>begin select * from DBSCHEMA.DB_VALIDITY_CHECK where CHECKER = 1 for update with rs; commit;</li>\n<li>begin select * from DBSCHEMA.DB_VALIDITY_CHECK where CHECKER = 1 for update; commit; end;</li>\n</ol>\n<p>the exact error is: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=*;begin select ;(, DRIVER=4.19.26</p>\n',
		},
		{
			tags: ['sql', 'db2'],
			owner: {
				account_id: 28407469,
				reputation: 7,
				user_id: 21731288,
				user_type: 'registered',
				profile_image:
					'https://www.gravatar.com/avatar/38dfce880d1f1acc4572eee5e1130440?s=256&d=identicon&r=PG&f=y&so-version=2',
				display_name: 'ZEHRA',
				link: 'https://stackoverflow.com/users/21731288/zehra',
			},
			is_answered: false,
			view_count: 30,
			answer_count: 0,
			score: 0,
			last_activity_date: 1682684559,
			creation_date: 1682682677,
			last_edit_date: 1682684559,
			question_id: 76129298,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/76129298/i-am-using-decode-function-in-db2-query-but-i-have-two-search-values-with-one-re',
			title:
				'I am using decode function in db2 query but I have two search values with one result value how can I optimize it',
			body: "<pre><code>select DISTINCT \n  DECODE(\n    A.FILE_MAINT_TRX_CD\n  , 'LARD','DELETE'\n  , 'LOBD','DELETE'\n  ) AS &quot;TRANSACTION_TYPE&quot;\n</code></pre>\n<p>&quot;how can I optimize this code as a result value in both search I am using delete&quot;</p>\n<p>earlier I was using case statement</p>\n<pre><code>select DISTINCT \n  CASE \n    WHEN (A.FILE_MAINT_TRX_CD = 'LARD' OR A.FILE_MAINT_TRX_CD = 'LOBD') \n    THEN 'DELETE' \n  END AS &quot;TRANSACTION_TYPE&quot;\n</code></pre>\n<p>to reduce query time I am using decode</p>\n",
		},
		{
			tags: ['sql', 'select', 'db2', 'sql-like', 'in-operator'],
			owner: {
				account_id: 1320127,
				reputation: 1872,
				user_id: 1266132,
				user_type: 'registered',
				accept_rate: 53,
				profile_image:
					'https://www.gravatar.com/avatar/ebbed530dc1d9552539ff28142561ea3?s=256&d=identicon&r=PG',
				display_name: 'Amin SCO',
				link: 'https://stackoverflow.com/users/1266132/amin-sco',
			},
			is_answered: true,
			view_count: 12994,
			answer_count: 4,
			score: 1,
			last_activity_date: 1682683431,
			creation_date: 1420458211,
			last_edit_date: 1420509734,
			question_id: 27778830,
			content_license: 'CC BY-SA 3.0',
			link: 'https://stackoverflow.com/questions/27778830/how-to-use-search-multiple-like-for-in-condition-in-db2',
			title: 'How to use Search multiple LIKE for IN condition in DB2',
			body: "<pre><code>  SELECT *\n  FROM XYZ\n  WHERE column1 IN (X1,Y1,Z1);\n</code></pre>\n\n<p>I want to use <strong>LIKE</strong> with this select query; how can I write <strong>LIKE</strong> statement with <strong>IN</strong>, similar to the query as below:</p>\n\n<pre><code>  SELECT * \n  FROM XYZ \n  WHERE column1 LIKE IN  ($P{COLUMN});\n</code></pre>\n\n<p><strong>ANOTHER EXAMPLE:-</strong></p>\n\n<blockquote>\n  <p>select * from ( select REPLACE(REFEV_VEH_TYPE, ' ', '') ||\n  REPLACE(REFEV_CATEGORY, ' ', '') || REPLACE(REFEV_USAGE, ' ', '') ||\n  REPLACE(REFEV_BODY_CODE, ' ', '') as  UC  from TREF_ENF_VEHICLE_TYPE )\n  aa where   aa.UC  LIKE ('%06TBISUM%')</p>\n</blockquote>\n\n<pre><code>UC\n------\n06TBISUM\n</code></pre>\n\n<blockquote>\n  <p>select * from ( select REPLACE(REFEV_VEH_TYPE, ' ', '') ||\n  REPLACE(REFEV_CATEGORY, ' ', '') || REPLACE(REFEV_USAGE, ' ', '') ||\n  REPLACE(REFEV_BODY_CODE, ' ', '') as  UC  from TREF_ENF_VEHICLE_TYPE )\n  aa where   aa.UC  LIKE ('%B')</p>\n</blockquote>\n\n<pre><code> UC\n----------\n06TGISJB\n06TGITJB\n</code></pre>\n\n<blockquote>\n  <p>select * from ( select REPLACE(REFEV_VEH_TYPE, ' ', '') ||\n  REPLACE(REFEV_CATEGORY, ' ', '') || REPLACE(REFEV_USAGE, ' ', '') ||\n  REPLACE(REFEV_BODY_CODE, ' ', '') as  UC  from TREF_ENF_VEHICLE_TYPE )\n  aa where   aa.UC  LIKE ('%BAS')</p>\n</blockquote>\n\n<pre><code>UC\n----------\n06BCIBAS\n05BCABAS\n05BCBBAS\n</code></pre>\n\n<p><strong>The result that i want to know is :</strong></p>\n\n<p>select * from (\nselect REPLACE(REFEV_VEH_TYPE, ' ', '') || REPLACE(REFEV_CATEGORY, ' ', '') || REPLACE(REFEV_USAGE, ' ', '') || REPLACE(REFEV_BODY_CODE, ' ', '') as  UC \nfrom TREF_ENF_VEHICLE_TYPE ) aa\nwhere   aa.UC IN LIKE (<strong>'%06TBISUM%', '%B','%BAS'</strong>).</p>\n\n<pre><code>UC\n------\n06TBISUM\n06TGISJB\n06TGITJB\n06BCIBAS\n05BCABAS\n05BCBBAS\n</code></pre>\n\n<p>The parameter that i use is <strong>$P{COLUMN}</strong>.\ni want to search multiple by <strong>$P{COLUMN}</strong> parameter using IN LIKE($P{COLUMN}).Anyone know about this?</p>\n",
		},
		{
			tags: ['database', 'db2'],
			owner: {
				account_id: 323082,
				reputation: 1,
				user_id: 642886,
				user_type: 'registered',
				profile_image:
					'https://www.gravatar.com/avatar/fc9a1d2f705693838e8e8d92af80db26?s=256&d=identicon&r=PG',
				display_name: 'Perry Christensen',
				link: 'https://stackoverflow.com/users/642886/perry-christensen',
			},
			is_answered: true,
			view_count: 540,
			answer_count: 2,
			score: 0,
			last_activity_date: 1682682862,
			creation_date: 1299154223,
			last_edit_date: 1682682862,
			question_id: 5180533,
			content_license: 'CC BY-SA 4.0',
			link: 'https://stackoverflow.com/questions/5180533/db2-express-c-9-7-2-consistency-failure-in-repeatable-read',
			title: 'DB2 Express-C 9.7.2 - consistency failure in Repeatable read',
			body: "<p>I'm doing a DB Tuning assignment where I run swaps of balances in accounts concurrently with a sum of all balances.</p>\n<p>My setup is that I run for instance 50 threads with 100 swaps.\nThe DB2 currently committed semantics is set to ON as in the default configuration.</p>\n<p>If I iterate the experiment enough times, I end up getting a consistency error i.e. the total sum of the balances are changed. Hence I must have had some lost updates.</p>\n<p>Lost updates should not be possible in repeatable read(?).</p>\n<p>As far as I understand currently committed semantics works as a snapshot isolation so that if another transaction is accessing data while the original transaction is writing, it uses the currently committed data and not uncommitted writes in the concurrently running transaction. This comes at a risk of lost updates. But according to what I can find in the db2 documentation this only applies to Cursor Stability.</p>\n<p>Now I get lost updates with Repeatable Read Isolation level. Does anyone have an idea why this is?</p>\n<p>EDIT:</p>\n<p><strong>swap1.sql:</strong></p>\n<pre><code>select balance from accounts where number = ? for update;\n</code></pre>\n<p><strong>swap2.sql:</strong></p>\n<pre><code>update accounts set balance = ? where number = ?;\n</code></pre>\n<p><strong>sum.sql:</strong></p>\n<pre><code>select sum(balance) from accounts;\n</code></pre>\n<p><strong>init.sql</strong></p>\n<pre><code>create table accounts(number integer not null primary key, branchnum integer not null, balance float not null);\n\n\n#!/usr/bin/env python\n# encoding: utf-8\n&quot;&quot;&quot;\nDB2/ValueOfSerializability/experiment.py\n\nimport sys\nimport getopt\nimport timeit\nimport multiprocessing\nimport random\nimport os\nimport ibm_db\nimport time\n\n\n### Experiment parameters (default values)\nNBRUNS         = 5          # Number of runs (-r:, --runs=)\nNBSWAPS        = 100        # Number of swaps (-s:, --swaps=)\nNBSWAPTHREADS  = 10         # Number of swap threads (-t:, --threads=)\nRANGE_LOW      = 1          # Lower bound of the range for account number\nRANGE_UP       = 1000000    # Upper bound of the range for account number\nISOL_LEVEL     = 'RR'\n\n### Output parameters (default values)\nOUTPUT_FILE_PATH  = '.'   # Path of the output file output.txt (append)\n\n### Database parameters (DATABASE; HOSTNAME; PORT; USERNAME; PASSWORD)\nsys.path.append(&quot;..&quot;)\nfrom db2 import *\n\n# Process Manager data structure\nq = None\n\n&quot;&quot;&quot;&quot;\nSwapping of balance values.\nread balance for account number X into valX and for account number Y into valY.\nupdate account number X with balance set to valY\nupdate account number Y with balance set to valX\nX &lt; Y\nWe avoid deadlocks because of the clustered index on\naccount number that garantees that account numbers\nare accessed in acending order.\n&quot;&quot;&quot;\ndef swap(q):\n    swap1_str= q[0]; swap2_str = q[1]\n    # Connect to DB\n    conn = ibm_db.pconnect(DATABASE, USERNAME, PASSWORD)\n    if conn is None: raise Usage(ibm_db.conn_errormsg())\n    ibm_db.autocommit(ibm_db.SQL_AUTOCOMMIT_OFF)\n    # Set isolation level\n    ret = ibm_db.exec_immediate(conn, &quot;SET CURRENT ISOLATION = &quot;+ISOL_LEVEL)\n    # Prepare Statements\n    swap1_stmt = ibm_db.prepare(conn, swap1_str)\n    if (swap1_stmt == False):\n        raise Usage(&quot;Failed to prepare swap1 query&quot;)\n    swap2_stmt = ibm_db.prepare(conn, swap2_str)\n    if (swap2_stmt == False):\n        raise Usage(&quot;Failed to prepare swap2 update&quot;)\n    # Execute Statements\n    nbrep = int(round(NBSWAPS / NBSWAPTHREADS))\n    for i in range(nbrep):\n        x = random.randint(RANGE_LOW, RANGE_UP/2)\n        y = random.randint(x,RANGE_UP)\n        if ibm_db.execute(swap1_stmt, (x,)) == False:\n            raise Usage(&quot;Failed to execute the swap1 query (x)&quot;)\n        valX = ibm_db.fetch_tuple(swap1_stmt)\n        if valX == False:\n            raise Usage(&quot;Failed to iterate over the swap1 result set (x)&quot;)\n        if ibm_db.execute(swap1_stmt, (y,)) == False:\n            raise Usage(&quot;Failed to execute the swap1 query (y)&quot;)\n        valY = ibm_db.fetch_tuple(swap1_stmt)\n        if valY == False:\n            raise Usage(&quot;Failed to iterate over the swap1 result set (y)&quot;)\n        time.sleep(0.1)\n        if ibm_db.execute(swap2_stmt, (valY[0],x)) == False:\n            raise Usage(&quot;Failed to execute the swap2 query (x, valY)&quot;)\n        if ibm_db.execute(swap2_stmt, (valX[0],y)) == False:\n            raise Usage(&quot;Failed to execute the swap1 query (y, valX)&quot;)\n        ibm_db.commit(conn)\n    # Disconnect from DB\n    status = ibm_db.close(conn)\n    if status == False: raise Usage(&quot;Failed to close db connection.\\n&quot;)\n\n\ndef summation(q):\n    sum_str = q[2]\n    # Connect to DB\n    conn = ibm_db.pconnect(DATABASE, USERNAME, PASSWORD)\n    if conn is None:\n        raise Usage(ibm_db.conn_errormsg())\n    ibm_db.autocommit(ibm_db.SQL_AUTOCOMMIT_OFF)\n    # Set isolation level\n    ret = ibm_db.exec_immediate(conn, &quot;SET CURRENT ISOLATION = &quot;+ISOL_LEVEL)\n    # Prepare statement\n    sum_stmt   = ibm_db.prepare(conn, sum_str)\n    if (sum_stmt == False): raise Usage(&quot;Failed to prepare sum query&quot;)\n    # Execute statement\n    if ibm_db.execute(sum_stmt) == False:\n        raise Usage(&quot;Failed to execute the sum query&quot;)\n    sum= ibm_db.fetch_tuple(sum_stmt)\n    ibm_db.commit(conn)\n    # Print result set to output file\n    try:\n      f = open(OUTPUT_FILE_PATH+'/output.txt', 'a')\n      f.write(str(sum)+'\\n')\n      f.close()\n    except IOError, e:\n      raise Usage(&quot;Failed to manipulate output.txt.\\n&quot;)\n    finally:\n      f.close()\n    # Disconnect from DB\n    status = ibm_db.close(conn)\n    if status == False: raise Usage(&quot;Failed to close db connection.\\n&quot;)\n\n&quot;&quot;&quot;\nThread wrapper class\n&quot;&quot;&quot;\nclass Thread(multiprocessing.Process):\n    def __init__(self, target, *args):\n        multiprocessing.Process.__init__(self, target=target, args=args)\n        self.start()\n\ndef experiment(q):\n    ThreadL = []\n    # Launch swap threads\n    for n in range(NBSWAPTHREADS):\n        ThreadL.append(Thread(swap,q))\n    # Launch Summation thread\n    ThreadL.append(Thread(summation, q))\n    # Barrier\n    for t in ThreadL:\n        t.join()\n\nhelp_message = '''\npython sumNswap.py [options]\noptions:\n-h, --help       : this help message\n-t, --threads=   : number of swap threads (1..59)\n-s, --swaps=     : total number of swaps (&lt; 1000)\n-r, --runs=      : number of repetitions (&lt; 100)\n-i, --isol=      : isolation level ('UR', 'CS', 'RS','RR')\n-o, --output=    : path to output file (result.txt)\n\nExecutes sum and swap transactions against the database described in ../db2.py\nand prints timing\n\nExample: python sumNswap.py -t10 -s1000 -r5 -iCS\n'''\n\nclass Usage(Exception):\n    def __init__(self, msg):\n        self.msg = msg\n\ndef main(argv=None):\n    global NBRUNS, NBSWAPS, NBSWAPTHREADS, RANGE_LOW, RANGE_UP, ISOL_LEVEL\n    global OUTPUT_FILE_PATH\n    global q\n    try:\n        if argv is None:\n            argv = sys.argv\n\n            try:\n                opts, args = getopt.getopt(argv[1:],\n                &quot;ho:vr:s:t:g:i:&quot;,\n                [&quot;help&quot;, &quot;output=&quot;, &quot;runs=&quot;,&quot;swaps=&quot;, &quot;threads=&quot;, &quot;isol=&quot;])\n            except getopt.error, msg:\n                raise Usage(msg)\n    \n        # Option processing\n        for option, value in opts:\n            if option == &quot;-v&quot;:\n                verbose = True\n            if option in (&quot;-h&quot;, &quot;--help&quot;):\n                raise Usage(help_message)\n            if option in (&quot;-r&quot;, &quot;--runs&quot;):\n                v = int(value)\n                if not (v &lt; 100): raise Usage(&quot;Runs out of bounds&quot;)\n                NBRUNS = v\n            if option in (&quot;-s&quot;, &quot;--swaps&quot;):\n                v = int(value)\n                if not (v &lt; 10000): raise Usage(&quot;Swaps out of bounds&quot;)\n                NBSWAPS = v\n            if option in (&quot;-t&quot;, &quot;--threads&quot;):\n                v = int(value)\n                if (v &lt; 0 or v&gt;60): raise Usage(&quot;Threads out of bounds&quot;)\n                NBSWAPTHREADS = v\n            if option in (&quot;-i&quot;, &quot;--isol&quot;):\n                if not value in ['UR', 'CS', 'RS', 'RR']: raise Usage(&quot;Isolation level not supported&quot;)\n                ISOL_LEVEL = value\n            if option in (&quot;-o&quot;, &quot;--output&quot;):\n                if not os.path.exists(value): raise Usage(&quot;Result file path does not exist&quot;)\n                OUTPUT_FILE_PATH= value\n    \n        # Verify preconditions: required sql files exist\n        try:\n            f = open('sum.sql', 'r')\n            sum_str = f.readline()\n            f.close()\n        except IOError, e:\n            raise Usage(&quot;Failed to manipulate sum.sql.\\n&quot;)\n    \n        try:\n            f = open('swap1.sql', 'r')\n            swap1_str = f.readline()\n            f.close()\n        except IOError, e:\n            raise Usage(&quot;Failed to manipulate swap1.sql.\\n&quot;)\n    \n        try:\n            f = open('swap2.sql', 'r')\n            swap2_str = f.readline()\n            f.close()\n        except IOError, e:\n            raise Usage(&quot;Failed to manipulate swap2.sql.\\n&quot;)\n    \n        print 'run (isol: '+ISOL_LEVEL+', threads: '+str(NBSWAPTHREADS)+', swaps:'+str(NBSWAPS)+')'\n        # Queue Initialization\n        manager = multiprocessing.Manager()\n        q = manager.list([swap1_str, swap2_str, sum_str])\n    \n        # Timed experiment\n        t = timeit.Timer(&quot;experiment(q)&quot;, &quot;from __main__ import experiment,q&quot;)\n        timings = []\n        try:\n            # repeat 1 experiment NBRUNS time - output is a list of timing\n            timings = t.repeat(NBRUNS,1)\n            # Log timing\n            for timing in timings:\n                s = str(timing)\n                print s        \n        except: \n            raise Usage(t.print_exc())\n            \n    except Usage, err:\n        print &gt;&gt; sys.stderr, sys.argv[0].split(&quot;/&quot;)[-1] + &quot;: &quot; + str(err.msg)\n        print &gt;&gt; sys.stderr, &quot;\\t for help use --help&quot;\n        return 2\n\nif __name__ == &quot;__main__&quot;:\n    sys.exit(main())\n</code></pre>\n",
		},
	],
	has_more: true,
	quota_max: 10000,
	quota_remaining: 9960,
};

export const answers = {
	items: [
		{
			owner: {
				account_id: 17320203,
				reputation: 106,
				user_id: 12545861,
				user_type: 'registered',
				profile_image:
					'https://www.gravatar.com/avatar/ed1de6dabfe372d5c73a4ea5eb811b1d?s=256&d=identicon&r=PG&f=1',
				display_name: 'Philippe',
				link: 'https://stackoverflow.com/users/12545861/philippe',
			},
			is_accepted: false,
			score: 0,
			last_activity_date: 1682919846,
			creation_date: 1682919846,
			answer_id: 76144941,
			question_id: 76144745,
			content_license: 'CC BY-SA 4.0',
			body: '<p>To display an image using Django Framework, use the \'<a href="https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#std-templatetag-static" rel="nofollow noreferrer">static</a>\' template tag.\nFor example:</p>\n<pre><code>{% load static %}\n&lt;img src=&quot;{% static \'my_app/example.jpg\' %}&quot; alt=&quot;My image&quot;&gt;\n</code></pre>\n<p>Assuming that your images are in the directory &quot;/my_project/store/static/store/img/&quot; (<a href="https://docs.djangoproject.com/en/4.2/intro/tutorial06/#customize-your-app-s-look-and-feel" rel="nofollow noreferrer">Django doc</a>). In your template code, change <code>&lt;img src=&quot;{{product.img.url}}&quot;&gt;</code> to:</p>\n<pre><code>&lt;img src=&quot;{% static \'store/img/product_image.jpg\' %}}&quot;&gt;\n</code></pre>\n<p>If you need more information about configuring static, you can consult this <a href="https://docs.djangoproject.com/en/4.2/howto/static-files/#configuring-static-files" rel="nofollow noreferrer">link</a>.</p>\n',
		},
	],
	has_more: false,
	quota_max: 10000,
	quota_remaining: 9949,
};

export const questionDetail = {
	items: [
		{
			owner: {
				account_id: 17320203,
				reputation: 106,
				user_id: 12545861,
				user_type: 'registered',
				profile_image:
					'https://www.gravatar.com/avatar/ed1de6dabfe372d5c73a4ea5eb811b1d?s=256&d=identicon&r=PG&f=1',
				display_name: 'Philippe',
				link: 'https://stackoverflow.com/users/12545861/philippe',
			},
			is_accepted: false,
			score: 0,
			last_activity_date: 1682919846,
			creation_date: 1682919846,
			answer_id: 76144941,
			question_id: 76144745,
			content_license: 'CC BY-SA 4.0',
			body: '<p>To display an image using Django Framework, use the \'<a href="https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#std-templatetag-static" rel="nofollow noreferrer">static</a>\' template tag.\nFor example:</p>\n<pre><code>{% load static %}\n&lt;img src=&quot;{% static \'my_app/example.jpg\' %}&quot; alt=&quot;My image&quot;&gt;\n</code></pre>\n<p>Assuming that your images are in the directory &quot;/my_project/store/static/store/img/&quot; (<a href="https://docs.djangoproject.com/en/4.2/intro/tutorial06/#customize-your-app-s-look-and-feel" rel="nofollow noreferrer">Django doc</a>). In your template code, change <code>&lt;img src=&quot;{{product.img.url}}&quot;&gt;</code> to:</p>\n<pre><code>&lt;img src=&quot;{% static \'store/img/product_image.jpg\' %}}&quot;&gt;\n</code></pre>\n<p>If you need more information about configuring static, you can consult this <a href="https://docs.djangoproject.com/en/4.2/howto/static-files/#configuring-static-files" rel="nofollow noreferrer">link</a>.</p>\n',
		},
	],
	has_more: false,
	quota_max: 10000,
	quota_remaining: 9940,
};
